name: Build APK with Buildozer

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-8-jdk \
            build-essential libncurses5 libstdc++6 \
            python3-pip

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer flet

      - name: Init buildozer
        run: |
          buildozer init
          sed -i 's/^#\(requirements = python3,kivy\)/requirements = python3,flet/' buildozer.spec
          sed -i 's/^#\(android.permissions = INTERNET\)/\1/' buildozer.spec

      - name: Build APK
        run: buildozer android debug
