name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer Requirements
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git zip unzip openjdk-8-jdk python3-pip libncurses5 libstdc++6
          pip install flet buildozer

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/^#\(source.include_exts = py,png,jpg,kv,atlas\)/\1/' buildozer.spec
          sed -i 's/^#\(requirements = python3,kivy\)/requirements = python3,flet/' buildozer.spec
          sed -i 's/^#\(android.permissions = INTERNET\)/\1/' buildozer.spec
          echo "main.py" > .gitignore
          buildozer -v android debug
